=== dimakhodosevich/XMLProject/src/com/itvdn/jdbcandhibernate/ex_002_formatting_and_validation_XML/country.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="root" type="rootType"/>

  <xs:complexType name="countryType">

    <xs:sequence>

      <xs:element name="name">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Belarus"/>
            <xs:enumeration value="Ukraine"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="capital">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Minsk"/>
            <xs:enumeration value="Kiev"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="description">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Belarus is..."/>
            <xs:enumeration value="Ukraine is..."/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

    </xs:sequence>

    <xs:attribute type="xs:string" name="countyCode" use="required"/>
  </xs:complexType>

  <xs:complexType name="rootType">
    <xs:sequence>
      <xs:element type="countryType" name="country" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== dimakhodosevich/XMLProject/src/com/itvdn/jdbcandhibernate/ex_002_formatting_and_validation_XML/country.xml
<?xml version="1.0" encoding="UTF-8" ?>


<!--<!DOCTYPE root [-->
<!--        <!ELEMENT root (country)*>-->
<!--        <!ELEMENT country (name|capital|description)*>-->
<!--        <!ATTLIST country-->
<!--                countyCode CDATA #REQUIRED>-->
<!--        <!ELEMENT name (#PCDATA)>-->
<!--        <!ELEMENT capital (#PCDATA)>-->
<!--        <!ELEMENT description (#PCDATA)>-->
<!--        ]>-->

<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="country.xsd">
    <country  countyCode="bel">
        <name>Belarus</name>
        <capital>Minsk</capital>
        <description>Belarus is...</description>

    </country>
    <country countyCode="ua">
        <name>Ukraine</name>
        <capital>Kiev</capital>
        <description>Ukraine is...</description>
    </country>

</root>
