=== dimakhodosevich/XMLProject/out/production/XMLProject/com/itvdn/webservices/ex_009_x_path/employees.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="employees" type="employeesType"/>

    <xs:complexType name="employeesType">
        <xs:sequence>
            <xs:element name="employee" type="emplType" maxOccurs="unbounded" minOccurs="0">
        </xs:sequence>

    </xs:complexType>

    <xs:complexType name="emplType">
        <xs:sequence>
            <xs:element name ="firstname" type="xs:string"></xs:element>
            <xs:element name ="lastname" type="xs:string"></xs:element>
            <xs:element name ="age" type="xs:integer"></xs:element>
            <xs:element name ="email" type="xs:string"></xs:element>
        </xs:sequence>

        <xs:attribute name = "id" type="xs:integer"></xs:attribute>
        <xs:attribute name = "type" type="xs:string"></xs:attribute>
    </xs:complexType>

</xs:schema>

=== dimakhodosevich/XMLProject/out/production/XMLProject/com/itvdn/webservices/ex_009_x_path/employees.xml
<?xml version="1.0" encoding="UTF-8" ?>

<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation ="employees.xsd">

    <employee id = "1" type = "admin">
        <firstname>Dima</firstname>
        <lastname>Khodosevich</lastname>
        <age>27</age>
        <email>dimakhodosevich95@gmail.com</email>
    </employee>

    <employee id = "2" type = "user">
        <firstname>Matvey</firstname>
        <lastname>Khodosevich</lastname>
        <age>19</age>
        <email>matveykhodosevich03@gmail.com</email>
    </employee>


</employees>
