=== dimakhodosevich/XMLProject/out/production/XMLProject/com/itvdn/webservices/ex_002_SAX_with_object_1/sandwich.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="root" type="rootType"/>

  <xs:complexType name="sendwichType">
    <xs:sequence>
      <xs:element type="xs:string" name="name"></xs:element>
      <xs:element type="xs:string" name="ingridient" minOccurs="0" maxOccurs="unbounded"></xs:element>
      <xs:element type="xs:double" name="cost"></xs:element>
      <xs:element type="xs:double" name="weight"></xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="rootType">
    <xs:sequence>
      <xs:element type="sendwichType" name="sendwich" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== dimakhodosevich/XMLProject/src/com/itvdn/webservices/ex_002_SAX_with_object_1/sandwich.xml
<?xml version="1.0" encoding="UTF-8" ?>

<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="sandwich.xsd">

    <sendwich>
        <name>double_gamburger</name>
        <ingridient>tomato</ingridient>
        <ingridient>beaf</ingridient>
        <ingridient>pasta</ingridient>
        <ingridient>zelen</ingridient>
        <cost>0.55</cost>
        <weight>150</weight>
    </sendwich>

</root>
